### PR TITLE
add Version property to BinTree

### PR DESCRIPTION
**Pull request by Rerago**
Adds a version property to `BinTree`. This allows to use it directly when writing (in case of fallback if no other version is explicitly specified).

### CODE REVIEW

**Comment by Morilli** [comment]
I agree that `BinTree` objects should have a public version property, however using the type `Version` is not proper (or useful), as that is only intended for assembly versions, and not arbitrary file format versions.
As the existing code is already using these `Version` types, I will make a commit that removes all references to this type and uses uints instead, while incorporating your changes, aka storing the version as a property.

**Comment by Rerago** [comment]
I am also not a friend of it. But you should have changed the functions like `Write`. And apart from that there is a `FileVersionProvider` which lists the supported versions. So it might be a bit more complicated to remove `Version` completely.

Or you would have to find a consistent line in the API, which is currently `Version`. If then you would have to rebuild it everywhere, which would be a bit more work.

**Comment by Rerago** [comment]
Oh you have already installed it. But then the support for e.g. 3.5 falls out (if there will be that).

**Comment by Rerago** [comment]
Oh you have already added it. But with this the support for versions like 3.5 is dropped (if there will be such a thing).

**Comment by Morilli** [comment]
> support for versions like 3.5 is dropped

Right, currently there are only `uint`s supported, but using the `Version` type is not the correct move either way. At best I would be implementing a custom `FileVersion` type which may be able to handle major and minor versions, or just provide those as individual fields in the object. But all those thoughts can come later if subversions are ever used.

**Pull request closed without merging**
