### PR TITLE
fixed TEXFile

### PR DESCRIPTION
**Pull request by 1369521908**

### CODE REVIEW

**Comment by Morilli** [comment]
What code conventions are you using here to generate this diff? And why is it necessary? Newlines after enum definitions and ifs I could accept, but why the namespace change, the removed newline and change from LF -> CRLF?

**Comment by 1369521908** [comment]
sorry about that format, LF is right , i use Rider for dev and default setting is CRLF...
and about the namespace change i use netstandard 2.1 for develop but occur some problem,
but at the previous version it run normally
image
image

**Comment by 1369521908** [comment]
here is after change the file and build the solution
image

**Comment by Morilli** [comment]
The namespace feature is of language version 10.0, aka .NET6+. Arguably the current setting of "preview" is ambiguous, because it points to a different version depending on what SDK version is installed. I think it's probably better to fix this to "9.0" (as there are no other version 10-specific features used at the moment) to allow building with the .NET5 SDK as well.

**Comment by 1369521908** [comment]
less use of .net and C#... seem confusionfor me with the version problem 
should i close the pr?

**Comment by Morilli** [comment]
> should i close the pr?

Probably easiest, however I will make a commit that changes this so it builds for you out-of-the-box.

**Comment by 1369521908** [comment]
ok thanks~

**Pull request closed without merging**
